name: iterate
on:
  workflow_dispatch:
   inputs:
      semverType:
        description: 'Which type of semver to release'
        required: true
        type: choice
        options:
          - 'prerelease'
          - 'patch'
          - 'minor'
          - 'major'

jobs:
   publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
              
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: iterate
        run: |
          MANIFEST_FILE=release/release-please-manifest.${{ inputs.semverType == 'prerelease' && 'prerelease' || 'prod' }}.json
          PACKAGES=$(jq -r 'keys[]' $MANIFEST_FILE)
          
          for KEY in $PACKAGES; do
            KEY_VALUE=$(jq -r ".\"$KEY\"" $MANIFEST_FILE)
            # Split KEY into array using '/' as delimiter
            IFS='/' read -ra KEY_PARTS <<< "$KEY"
            
            PACKAGE_NAME=${KEY_PARTS[0]}

            echo "Processing: $KEY: $KEY_VALUE"

            echo "package: $PACKAGE_NAME"
            
            cd $KEY
            echo npm pack
            echo gh release upload ${PACKAGE_NAME}-v$KEY_VALUE ${PACKAGE_NAME}-$KEY_VALUE.tgz
            cd ../..
          done

      # - name: NPM Publish
      #   if: ${{ steps.release.outputs.release_created }}
      #   run: npm pack
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # - name: Upload Release Artifact
      #   if: ${{ steps.release.outputs.release_created }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RP_TOKEN }}
      #   run: gh release upload ${{ steps.release.outputs.tag_name }} package-a-0.0.1-next.27.tgz

