name: prepare-release-major
on:
  workflow_dispatch

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RP_TOKEN }}
          config-file: release/release-please-config.major.json
          manifest-file: release/release-please-manifest.json
