name: prepare-release-next
on:
  workflow_dispatch

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RP_TOKEN }}
          config-file: release-please-config.next.json
